# Indentation: 4 spaces, NO tabs
# Comments start with #
# Empty values are indicated with ~

# These parameters can be imported into other config files
# by enclosing the key with % (like %database_user%)
parameters:
    locale: bg

    database_host: localhost
    database_name: chitanka
    database_user: chitanka
    database_password: ~
    database_driver: pdo_mysql
    database_port: null

    # database file for sqlite
    database_path: "%kernel.root_dir%/../web/content/chitanka.db"

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    orm_metadata_cache_driver: array
    orm_result_cache_driver: array
    orm_query_cache_driver: array
    orm_region_cache_driver: apcu
    second_level_cache_enabled: false

    # Следните променливи се ползват при пращането на електронна поща
    admin:              Администратор
    admin_email:        admin@localhost
    site_email:         admin@localhost
    work_email:         admin@localhost

    assets_base_urls: ~
    asset_version: 1
    style_path:  /css/?
    js_path:  /js/?
    thumb_path:  /thumb/?
    # Път до библиотеката jQuery. По подразбиране false.
    # При false, се ползва локалното копие
    script_library: false

    update_db_url: http://api.chitanka.info/db

    admin_max_per_page: 15

    sitename:    Моята библиотека

    webroot: ~
    docroot: ~

    # This must be a valid timezone constant
    # See “List of Supported Timezones” [http://php.net/manual/en/timezones.php]
    default_timezone: Europe/Sofia

    download_formats: [txt.zip, fb2.zip, epub, sfb.zip]
    download_file: AUTHOR - SERIES - SERNO. TITLE-ID

    workroom_remote: false
    workroom_root: ~
    workroom_url: http://workroom.chitanka.info
    workroom_ban_year_threshold: 2100

    biblioman_url: //biblioman.chitanka.info/books/$1
    wiki_url: http://wiki.chitanka.info/$1

    # used for posting of notifications to a rocket.chat instance
    rocketchat.url: ~
    rocketchat.notifications_channel: ~ # here we will post our notifications
    rocketchat.password: ~
    rocketchat.username: ~

    mirror_sites: ~

    global_info_message: Това е огледало на <a href="http://chitanka.info">Моята библиотека</a>.
    analytics_snippet: ~
    use_http_cache: false
    allow_user_registration: false
    allow_remote_wiki_article: true
    allow_removed_notice: false
    dev.web_profiler_toolbar: false
    git.path: /usr/bin/git
    rsync.path: /usr/bin/rsync
    rsync.url: rsync.chitanka.info::content
    content_dir: %kernel.root_dir%/../web/content
    content_web_dir: content # not used at the moment
    content_urls:
        book: https://github.com/chitanka/content-book.git
        book-anno: https://github.com/chitanka/content-book-anno.git
        book-cover: https://github.com/chitanka/content-book-cover.git
        book-djvu: https://github.com/chitanka/content-book-djvu.git
        book-img: https://github.com/chitanka/content-book-img.git
        book-info: https://github.com/chitanka/content-book-info.git
        book-pdf: https://github.com/chitanka/content-book-pdf.git
        book-pic: https://github.com/chitanka/content-book-pic.git
        img: https://github.com/chitanka/content-img.git
        misc: https://github.com/chitanka/content-misc.git
        text: https://github.com/chitanka/content-text.git
        text-anno: https://github.com/chitanka/content-text-anno.git
        text-info: https://github.com/chitanka/content-text-info.git
        user: https://github.com/chitanka/content-user.git
        wiki: https://github.com/chitanka/content-wiki.git

    project_links:
        //chitanka.info: Библиотека
        //biblioman.chitanka.info: Библиоман
        //smehurko.chitanka.info: Смехурко
        //forum.chitanka.info: Форум
        //chat.chitanka.info: Чат
        //prevodi.chitanka.info: Дачко
        //wiki.workroom.chitanka.info: Читалие
        //rechnik.chitanka.info: Речник
        //gramofonche.chitanka.info: Грамофонче
        //tools.chitanka.info: Сръчко

    main.dashboard:
        authors:
            icon: users
        translators:
            icon: edit
        books:
            icon: book
        texts:
            icon: folder-open
        series:
            icon: sitemap
        new:
            icon: calendar
        workroom:
            icon: table
    main.sections:
        - books
        - texts
        #- liter_posts
        #- searches
        #- comments
        #- forum_posts
